env:
  HUB_USERNAME: foobar
  HUB_PASSWORD: sup3r_s3cr3t
  S3_ACCESS_KEY: admin
  S3_SECRET_KEY: s3cr3t_p4ssw0rd
  S3_USE_SSL: false
  S3_BUCKET: flame
  OIDC_CERTS_URL: http://keycloak-service/realms/flame/protocol/openid-connect/certs
