apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-local-seaweedfs-service"
spec:
  type: NodePort  # setting nodePort later is optional
  selector:
    app: "{{ .Release.Name }}-seaweedfs"
  ports:
    - protocol: TCP
      port: 8333  # port of this service
      targetPort: http-s3  # port on the pod
