name: Create and publish Docker image from dev branch

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create and publish Docker image from dev branch
        uses: ./.github/actions/build-push-docker-image
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extra_tag: "edge"
