name: Integration test

env:
  S3_ROOT_USER: admin
  S3_ROOT_PASSWORD: s3cr3t_p4ssw0rd
  S3_LOCAL_BUCKET_NAME: flame
  POSTGRES_USER: flame
  POSTGRES_PASSWORD: s3cr3t_p4ssw0rd
  POSTGRES_DB: flame
  # Point these to the new dev instance of the FLAME Hub
  HUB_CORE_BASE_URL: https://core.privateaim.dev
  HUB_STORAGE_BASE_URL: https://storage.privateaim.dev
  HUB_AUTH_BASE_URL: https://auth.privateaim.dev

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
      - name: Install dependencies
        run: poetry install
      - name: Copy environment variables
        run: cp .env.example .env.test
      - name: Run tests
        run: poetry run pytest -vra -m "not live"
        env:
          S3__ACCESS_KEY: ${{env.S3_ROOT_USER}}
          S3__SECRET_KEY: ${{env.S3_ROOT_PASSWORD}}
          S3__BUCKET: ${{env.S3_LOCAL_BUCKET_NAME}}
          S3__ENDPOINT: localhost:8333
          HUB__AUTH__FLOW: client
          HUB__AUTH__ID: ${{secrets.HUB_CLIENT_ID}}
          HUB__AUTH__SECRET: ${{secrets.HUB_CLIENT_SECRET}}
          POSTGRES__HOST: localhost
          POSTGRES__USER: ${{env.POSTGRES_USER}}
          POSTGRES__PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES__DB: ${{env.POSTGRES_DB}}
          # Disable test containers.
          PYTEST__USE_TESTCONTAINERS: 0
          # No tests against live infra are run here but these envs are set anyway to future-proof in case
          # we ever end up testing against live infra. python-dotenv will not override existing envs so the prod
          # URLs in the .env.example file shouldn't carry over here.
          HUB__AUTH_BASE_URL: ${{env.HUB_AUTH_BASE_URL}}
          HUB__CORE_BASE_URL: ${{env.HUB_CORE_BASE_URL}}
          HUB__STORAGE_BASE_URL: ${{env.HUB_STORAGE_BASE_URL}}

    services:
      seaweedfs:
        image: chrislusf/seaweedfs:4.39
        env:
          AWS_ACCESS_KEY_ID: ${{env.S3_ROOT_USER}}
          AWS_SECRET_ACCESS_KEY: ${{env.S3_ROOT_PASSWORD}}
          S3_BUCKET: ${{env.S3_LOCAL_BUCKET_NAME}}
        ports:
          - 8333:8333

      postgres:
        image: postgres:17.2
        env:
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
