name: Lint OpenAPI schema file with Spectral

# Reactivate this workflow when the Spectral CLI is compatible with Node22.
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - develop
#  pull_request:
#    branches:
#      - main
#      - develop

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
      - name: Install dependencies
        run: poetry install
      - name: Create schema file
        run: poetry run openapi-spec openapi.json
      - name: Lint schema file
        run: npx @stoplight/spectral-cli@6 lint openapi.json --fail-severity=warn
